### ISSUE TITLE
Adicionar um processo de "pre-commit"

### ISSUE THREAD

**Issue by thehacktour5** [Finange/finange-bot#27]
Basicamente, precisamos adicionar essa biblioteca no nosso projeto [https://pre-commit.com/](url) com intuito de rever os erros do projeto antes de subir cada commit.

Ela também ajusta a sintaxe do código e revisa os teste unitarios para ver se todos passaram.

**Comment by Luiz-Edu0202** [comment]
Deixa essa comigo

**Comment by Luiz-Edu0202** [comment]
https://www.youtube.com/watch?v=Wmw-VGSjSNg pra quem quiser entender melhor
