### ISSUE TITLE
Criar uma função que faça o calculo do INSS do usuario

### ISSUE THREAD

**Issue by thehacktour5** [Finange/finange-bot#30]
Aqui a ideia é simplesmente receber do usuario o salario dele e fazer o calculo do INSS para ver quanto o usuario tem que pagar de INSS mensalmente, baseado no calculo da receita federal.

Você pode analisar esse calculo aqui: [https://www.idinheiro.com.br/calculadoras/calculadora-inss/](url)

**Comment by eddyyxxyy** [comment]
Vou tentar implementar isso.
