### ISSUE TITLE
Criar função para calcular o FGTS da pessoa.

### ISSUE THREAD

**Issue by thehacktour5** [Finange/finange-bot#31]
Aqui o contexto é simples:

Todo mês, quem é funcionário CLT, a empresa coloca 8% do salário da pessoa no FGTS, e, quando a pessoa é demitida ou pede demissão, ela tem direito a esse valor (que fica preso no ambo, dependendo do caso, mas, não é importante aqui). O importante pro nosso bot é fazer o calculo de quanto a pessoa vai ter direito desse FGTS após sair do emprego CLT.

Basicamente, vamos criar uma função para fazer esse calculo seguindo essa logica: [https://fdr.com.br/calculadora/fgts/](url)

**Comment by Luiz-Edu0202** [comment]
vou tentar fazer essa aqu

**Comment by Luiz-Edu0202** [comment]
para se alguém for mexer nisso depois um site bom pra ter algumas infos de fgts e calcular ele e testar.
Caixa: https://calculojuridico.com.br/calculadora-fgts-saldo/
