### ISSUE TITLE
Adicionar docstrings no codigo

### ISSUE THREAD

**Issue by thehacktour5** [Finange/finange-bot#34]
Aqui a ideia é ter explicação de todas as partes do codigo, detalhando o que cada parte faz.

E a maneira "pythonica" de fazer isso é com uso de "docstrings".

Coloque as explicações em português, uma vez que nosso projeto é br e para iniciantes. E use suas palavras.

**Comment by davilos** [comment]
Pode deixar esse comigo, mestre.
